### ISSUE TITLE
Estimated time of arrival doesn't update after departure

### ISSUE THREAD

**Issue by Arquiteto** [AlexandrErohin/home-assistant-flightradar24#86]
I was trying to setup an automation for family member flying in to pick them up. While setting things up I have set up some trial automations so I added 2 flights to track that were only scheduled at the time I added them. I noticed that after the tracks went live the "Time estimated arrival" attribute stayed null even after departure. I had to remove the flight from tracking and add it again for the attribute to appear correctly.

**Comment by AlexandrErohin** [comment]
This integration updates detailed flight info only after taking off - to prevent multiple FlightRadar API calls on every scan interval update. FlightRadar provides only few fields per flight when getting flights in the area. And these times not in these fields. If the integration would get full update on every flight which in the area at every scan interval update - You will get banned by IP by FlightRadar because of multiple calls.

But this times after take off may stay NULL. And FlightRadar may updates it after some time after take off

**Comment by AlexandrErohin** [comment]
@Arquiteto I have added additional update after take off - Please try v1.23.0
P.S. Would be great if you could give a star to the repo :) Thanks
